##############################
#    StarFarming v1.0.5      #
#       Made by csdad        #
##############################

# toggle a sidebar scoreboard displaying varying information.
# leave this false if your servers uses another scoreboard manager // plugin
# as it will override it.
toggle-scoreboard: true

# the title of the scoreboard
scoreboard-title: "&6&lStar&a&lFarming"

# the base experience required for level 1. 
base-xp: 1000

# the rate of increase between levels. if you want a breakdown of the formula, refer to the wiki
# on the resource's github.
roi: 1.75


# crop config section
# this section is where we add custom crops
# every value here is REQUIRED. If a value is configured incorrectly
# a crop will either not work, or won't be registered to memory.

# more on what each value means on the wiki on our github

crops:
  sweet_potato:
    name: "&cSweet Potato"
    material: POTATO
    growth_time: 1
    drop_chance: .25
    xp_per: 5
    base: 1
    spread: 6
    seasons:
      - "SPRING"
      - "FALL"
      - "SUMMER"
    product:
      material: POTATO
      name: "&6Sweet Potato Harvest"
      sell_price: 20
  raw_cane:
    name: "&eRaw Cane"
    material: SUGAR_CANE
    growth_time: 30
    drop_chance: .02
    xp_per: 75
    base: 1
    spread: 10
    seasons:
      - "SPRING"
      - "SUMMER"
    product:
      material: SUGAR_CANE
      name: "&6Raw Cane Harvest"
      sell_price: 100